import {int} from "../../types.js";

export const DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY = int;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_OTHER = -1;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HD15 = 0;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SVIDEO = 1;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPOSITE_VIDEO = 2;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_COMPONENT_VIDEO = 3;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DVI = 4;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI = 5;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_LVDS = 6;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_D_JPN = 8;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDI = 9;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL = 10;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EMBEDDED = 11;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EXTERNAL = 12;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_UDI_EMBEDDED = 13;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_SDTVDONGLE = 14;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_MIRACAST = 15;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_WIRED = 16;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_VIRTUAL = 17;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL = 0x80000000;
export const DISPLAYCONFIG_OUTPUT_TECHNOLOGY_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_SCANLINE_ORDERING = int;
export const DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED = 0;
export const DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE = 1;
export const DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED = 2;
export const DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST = DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED;
export const DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST = 3;
export const DISPLAYCONFIG_SCANLINE_ORDERING_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_SCALING = int;
export const DISPLAYCONFIG_SCALING_IDENTITY = 1;
export const DISPLAYCONFIG_SCALING_CENTERED = 2;
export const DISPLAYCONFIG_SCALING_STRETCHED = 3;
export const DISPLAYCONFIG_SCALING_ASPECTRATIOCENTEREDMAX = 4;
export const DISPLAYCONFIG_SCALING_CUSTOM = 5;
export const DISPLAYCONFIG_SCALING_PREFERRED = 128;
export const DISPLAYCONFIG_SCALING_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_ROTATION = int;
export const DISPLAYCONFIG_ROTATION_IDENTITY = 1;
export const DISPLAYCONFIG_ROTATION_ROTATE90 = 2;
export const DISPLAYCONFIG_ROTATION_ROTATE180 = 3;
export const DISPLAYCONFIG_ROTATION_ROTATE270 = 4;
export const DISPLAYCONFIG_ROTATION_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_MODE_INFO_TYPE = int;
export const DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1;
export const DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 2;
export const DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE = 3;
export const DISPLAYCONFIG_MODE_INFO_TYPE_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_PIXELFORMAT = int;
export const DISPLAYCONFIG_PIXELFORMAT_8BPP = 1;
export const DISPLAYCONFIG_PIXELFORMAT_16BPP = 2;
export const DISPLAYCONFIG_PIXELFORMAT_24BPP = 3;
export const DISPLAYCONFIG_PIXELFORMAT_32BPP = 4;
export const DISPLAYCONFIG_PIXELFORMAT_NONGDI = 5;
export const DISPLAYCONFIG_PIXELFORMAT_FORCE_UINT32 = 0xffffffff;

export const DISPLAYCONFIG_TOPOLOGY_ID = int;
export const DISPLAYCONFIG_TOPOLOGY_INTERNAL = 0x00000001;
export const DISPLAYCONFIG_TOPOLOGY_CLONE = 0x00000002;
export const DISPLAYCONFIG_TOPOLOGY_EXTEND = 0x00000004;
export const DISPLAYCONFIG_TOPOLOGY_EXTERNAL = 0x00000008;
export const DISPLAYCONFIG_TOPOLOGY_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_DEVICE_INFO_TYPE = int;
export const DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1;
export const DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2;
export const DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3;
export const DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4;
export const DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5;
export const DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6;
export const DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION = 7;
export const DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION = 8;
export const DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO = 9;
export const DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE = 10;
export const DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL = 11;
export const DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32 = 0xFFFFFFFF;

export const DISPLAYCONFIG_COLOR_ENCODING = int;
export const DISPLAYCONFIG_COLOR_ENCODING_RGB = 0;
export const DISPLAYCONFIG_COLOR_ENCODING_YCBCR444 = 1;
export const DISPLAYCONFIG_COLOR_ENCODING_YCBCR422 = 2;
export const DISPLAYCONFIG_COLOR_ENCODING_YCBCR420 = 3;
export const DISPLAYCONFIG_COLOR_ENCODING_INTENSITY = 4;
export const DISPLAYCONFIG_COLOR_ENCODING_FORCE_UINT32 = 0xFFFFFFFF;
