import {CHAR, HANDLE, LPCSTR, LPCWSTR, LPSTR, LPWSTR, WCHAR} from "../winnt.h/winnt.js";
import {BOOL, DWORD, LPDWORD, LPVOID, LPWORD, UINT, WORD} from "../minwindef.h/minWindef.js";
import {COORD, PCHAR_INFO, PSMALL_RECT} from "../wincontypes.h/wincontypes.js";

export function FillConsoleOutputCharacterA (hConsoleOutput: HANDLE, cCharacter: CHAR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function FillConsoleOutputCharacterW (hConsoleOutput: HANDLE, cCharacter: WCHAR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function FillConsoleOutputCharacter (hConsoleOutput: HANDLE, cCharacter: WCHAR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function FillConsoleOutputAttribute (hConsoleOutput: HANDLE, wAttribute: WORD, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfAttrsWritten: LPDWORD): BOOL;
export function GenerateConsoleCtrlEvent (dwCtrlEvent: DWORD, dwProcessGroupId: DWORD): BOOL;
export function CreateConsoleScreenBuffer (dwDesiredAccess: DWORD, dwShareMode: DWORD, lpSecurityAttributes: "SECURITY_ATTRIBUTES*", dwFlags: DWORD, lpScreenBufferData: LPVOID): HANDLE;
export function SetConsoleActiveScreenBuffer (hConsoleOutput: HANDLE): BOOL;
export function FlushConsoleInputBuffer (hConsoleInput: HANDLE): BOOL;
export function SetConsoleCP (wCodePageID: UINT): BOOL;
export function SetConsoleOutputCP (wCodePageID: UINT): BOOL;
export function GetConsoleCursorInfo (hConsoleOutput: HANDLE, lpConsoleCursorInfo: PCONSOLE_CURSOR_INFO): BOOL;
export function SetConsoleCursorInfo (hConsoleOutput: HANDLE, lpConsoleCursorInfo: "CONSOLE_CURSOR_INFO*"): BOOL;
export function GetConsoleScreenBufferInfo (hConsoleOutput: HANDLE, lpConsoleScreenBufferInfo: PCONSOLE_SCREEN_BUFFER_INFO): BOOL;
export function GetConsoleScreenBufferInfoEx (hConsoleOutput: HANDLE, lpConsoleScreenBufferInfoEx: PCONSOLE_SCREEN_BUFFER_INFOEX): BOOL;
export function SetConsoleScreenBufferInfoEx (hConsoleOutput: HANDLE, lpConsoleScreenBufferInfoEx: PCONSOLE_SCREEN_BUFFER_INFOEX): BOOL;
export function SetConsoleScreenBufferSize (hConsoleOutput: HANDLE, dwSize: COORD): BOOL;
export function SetConsoleCursorPosition (hConsoleOutput: HANDLE, dwCursorPosition: COORD): BOOL;
export function GetLargestConsoleWindowSize (hConsoleOutput: HANDLE): COORD;
export function SetConsoleTextAttribute (hConsoleOutput: HANDLE, wAttributes: WORD): BOOL;
export function SetConsoleWindowInfo (hConsoleOutput: HANDLE, bAbsolute: BOOL, lpConsoleWindow: "SMALL_RECT*"): BOOL;
export function WriteConsoleOutputCharacterA (hConsoleOutput: HANDLE, lpCharacter: LPCSTR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function WriteConsoleOutputCharacterW (hConsoleOutput: HANDLE, lpCharacter: LPCWSTR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function WriteConsoleOutputCharacter (hConsoleOutput: HANDLE, lpCharacter: LPCWSTR, nLength: DWORD, dwWriteCoord: COORD, lpNumberOfCharsWritten: LPDWORD): BOOL;
export function WriteConsoleOutputAttribute (hConsoleOutput: HANDLE, lpAttribute: "WORD*", nLength: DWORD, dwWriteCoord: COORD, lpNumberOfAttrsWritten: LPDWORD): BOOL;
export function ReadConsoleOutputCharacterA (hConsoleOutput: HANDLE, lpCharacter: LPSTR, nLength: DWORD, dwReadCoord: COORD, lpNumberOfCharsRead: LPDWORD): BOOL;
export function ReadConsoleOutputCharacterW (hConsoleOutput: HANDLE, lpCharacter: LPWSTR, nLength: DWORD, dwReadCoord: COORD, lpNumberOfCharsRead: LPDWORD): BOOL;
export function ReadConsoleOutputCharacter (hConsoleOutput: HANDLE, lpCharacter: LPWSTR, nLength: DWORD, dwReadCoord: COORD, lpNumberOfCharsRead: LPDWORD): BOOL;
export function ReadConsoleOutputAttribute (hConsoleOutput: HANDLE, lpAttribute: LPWORD, nLength: DWORD, dwReadCoord: COORD, lpNumberOfAttrsRead: LPDWORD): BOOL;
export function WriteConsoleInputA (hConsoleInput: HANDLE, lpBuffer: "INPUT_RECORD*", nLength: DWORD, lpNumberOfEventsWritten: LPDWORD): BOOL;
export function WriteConsoleInputW (hConsoleInput: HANDLE, lpBuffer: "INPUT_RECORD*", nLength: DWORD, lpNumberOfEventsWritten: LPDWORD): BOOL;
export function WriteConsoleInput (hConsoleInput: HANDLE, lpBuffer: "INPUT_RECORD*", nLength: DWORD, lpNumberOfEventsWritten: LPDWORD): BOOL;
export function ScrollConsoleScreenBufferA (hConsoleOutput: HANDLE, lpScrollRectangle: "SMALL_RECT*", lpClipRectangle: "SMALL_RECT*", dwDestinationOrigin: COORD, lpFill: "CHAR_INFO*"): BOOL;
export function ScrollConsoleScreenBufferW (hConsoleOutput: HANDLE, lpScrollRectangle: "SMALL_RECT*", lpClipRectangle: "SMALL_RECT*", dwDestinationOrigin: COORD, lpFill: "CHAR_INFO*"): BOOL;
export function ScrollConsoleScreenBuffer (hConsoleOutput: HANDLE, lpScrollRectangle: "SMALL_RECT*", lpClipRectangle: "SMALL_RECT*", dwDestinationOrigin: COORD, lpFill: "CHAR_INFO*"): BOOL;
export function WriteConsoleOutputA (hConsoleOutput: HANDLE, lpBuffer: "CHAR_INFO*", dwBufferSize: COORD, dwBufferCoord: COORD, lpWriteRegion: PSMALL_RECT): BOOL;
export function WriteConsoleOutputW (hConsoleOutput: HANDLE, lpBuffer: "CHAR_INFO*", dwBufferSize: COORD, dwBufferCoord: COORD, lpWriteRegion: PSMALL_RECT): BOOL;
export function WriteConsoleOutput (hConsoleOutput: HANDLE, lpBuffer: "CHAR_INFO*", dwBufferSize: COORD, dwBufferCoord: COORD, lpWriteRegion: PSMALL_RECT): BOOL;
export function ReadConsoleOutputA (hConsoleOutput: HANDLE, lpBuffer: PCHAR_INFO, dwBufferSize: COORD, dwBufferCoord: COORD, lpReadRegion: PSMALL_RECT): BOOL;
export function ReadConsoleOutputW (hConsoleOutput: HANDLE, lpBuffer: PCHAR_INFO, dwBufferSize: COORD, dwBufferCoord: COORD, lpReadRegion: PSMALL_RECT): BOOL;
export function ReadConsoleOutput (hConsoleOutput: HANDLE, lpBuffer: PCHAR_INFO, dwBufferSize: COORD, dwBufferCoord: COORD, lpReadRegion: PSMALL_RECT): BOOL;
export function GetConsoleTitleA (lpConsoleTitle: LPSTR, nSize: DWORD): DWORD;
export function GetConsoleTitleW (lpConsoleTitle: LPWSTR, nSize: DWORD): DWORD;
export function GetConsoleTitle (lpConsoleTitle: LPWSTR, nSize: DWORD): DWORD;
export function GetConsoleOriginalTitleA (lpConsoleTitle: LPSTR, nSize: DWORD): DWORD;
export function GetConsoleOriginalTitleW (lpConsoleTitle: LPWSTR, nSize: DWORD): DWORD;
export function GetConsoleOriginalTitle (lpConsoleTitle: LPWSTR, nSize: DWORD): DWORD;
export function SetConsoleTitleA (lpConsoleTitle: LPCSTR): BOOL;
export function SetConsoleTitleW (lpConsoleTitle: LPCWSTR): BOOL;
export function SetConsoleTitle (lpConsoleTitle: LPCWSTR): BOOL;
