export default {
	treeshake: {
		annotations: true,
		propertyReadSideEffects: false,
		manualPureFunctions: [
			"BigInt",
			"BigInt.asIntN",
			"BigInt.asUintN",
			"BigInt.prototype.toString",

			"debug", "createDebug",

			"koffi.config",
			"koffi.stats",
			"koffi.struct",
			"koffi.pack",
			"koffi.union",
			"koffi.Union",
			"koffi.opaque",
			"koffi.pointer",
			"koffi.array",
			"koffi.proto",
			"koffi.alias",
			"koffi.sizeof",
			"koffi.alignof",
			"koffi.offsetof",
			"koffi.resolve",
			"koffi.introspect",
			"koffi.load",
			"koffi.in",
			"koffi.out",
			"koffi.inout",
			"koffi.disposable",
			"koffi.alloc",
			"koffi.free",
			"koffi.register",
			"koffi.unregister",
			"koffi.as",
			"koffi.decode",
			"koffi.address",
			"koffi.call",
			"koffi.encode",
			"koffi.view",
			"koffi.reset",
			"koffi.errno",
		],
	},
	external: ["koffi", "debug"],
};
